name: Mi Primer Workflow
# 1. ¿Cuándo se ejecuta? Al hacer push a la rama 'main'
on:
 push:
 branches: [ main ]
# 2. ¿Qué va a hacer?
jobs:
 saludo:
 # Tipo de máquina virtual que usaremos
 runs-on: ubuntu-latest
 # Pasos secuenciales
 steps:
 - name: Imprimir saludo en consola
 run: echo "¡Hola Mundo! Tu GitHub Action funciona perfectamente."
 - name: Mostrar la fecha actual
 run: date