name: Test Multi-Versión con Secretos on: [push]
jobs:
test-matriz:
runs-on: ubuntu-latest

# Matriz: Ejecutará este Job 3 veces en paralelo (con Node 18, 20 y 22) strategy:
matrix:
node-version: [18, 20, 22]

steps:
-	name: Clonar repositorio uses: actions/checkout@v4
-	name: Configurar Node.js ${{ matrix.node-version }} uses: actions/setup-node@v4
with:
node-version: ${{ matrix.node-version }}
-	name: Instalar dependencias run: npm install

# Ejecutamos el test inyectando una API Key secreta guardada en GitHub
-	name: Ejecutar integración con API Externa env:
SUPER_SECRET_API_KEY: ${{ secrets.MI_API_KEY }}
run: npm run test:integration

